import nock from 'nock'

import farfetch from '../src'

afterAll(() => {
  nock.cleanAll()
})

const URL_TEST = 'http://api.localhost'
const API_TEST = '/login/'

const fetch = farfetch.api(URL_TEST)

function returnRequestHeaders() {
  return this.req.headers
}

test('rejects with status code != 2XX', async () => {
  nock(URL_TEST).get(API_TEST).reply(400, returnRequestHeaders)
  expect(fetch.get(API_TEST).catch(() => { throw new Error() })).toThrow()
})

test('fetches without baseURL', async () => {
  nock('http://other-api.localhost').get('/login/').reply(200, returnRequestHeaders)
  const request = await fetch.get('http://other-api.localhost/login/', { noBaseURL: true })
  expect(request.host).toBe('other-api.localhost')
})

test('has default content-type header and has no Authorization header', async () => {
  nock(URL_TEST).get(API_TEST).reply(200, returnRequestHeaders)

  const request = await fetch.get(API_TEST)

  expect(request['content-type'][0]).toBe('application/json; charset=UTF-8')
  expect(request.authorization).toBeFalsy()
})

test('has custom content-type header', async () => {
  nock(URL_TEST).get(API_TEST).reply(200, returnRequestHeaders)

  const request = await fetch.get(API_TEST, {
    headers: {
      'Content-type': 'text/html',
    },
  })
  expect(request['content-type'][0]).toBe('text/html')
})

test('has overrided Authorization headers (ignores `key`)', async () => {
  nock(URL_TEST).get(API_TEST).reply(200, returnRequestHeaders)

  const request = await fetch.get(API_TEST, {
    key: 'ABCDEFG',
    headers: {
      Authorization: 'Token ABCDEFGH',
    },
  })

  expect(request.authorization[0]).toBe('Token ABCDEFGH')
})

test('has Authorization header generated by `key` option', async () => {
  nock(URL_TEST).get(API_TEST).reply(200, returnRequestHeaders)

  const request = await fetch.get(API_TEST, { key: 'banana' })

  expect(request.authorization[0]).toBe('Token banana')
})

const defaults = { method: 'PUT', headers: { 'content-type': 'leleo', 'some-other-header': '123' } }
const fetchWithDefaults = farfetch.api(URL_TEST, defaults)

test('has default content-type header', async () => {
  nock(URL_TEST).put(API_TEST).reply(200, returnRequestHeaders)

  const request = await fetchWithDefaults.request(API_TEST)

  expect(request['content-type'][0]).toBe('leleo')
  expect(request['some-other-header'][0]).toBe('123')
})
